#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
from pathlib import Path

import sa_id
from sa_util import extract_frontmatter_value, write_text_atomic


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(prog="sa_index.py", description="生成 superagents/.sa/wiki 下的索引文件（generated）")
    p.add_argument("--root", default=".", help="项目根目录（默认：当前目录）")
    p.add_argument("--dir", default="superagents", help="superagents 目录名（默认：superagents）")
    p.add_argument("--check", action="store_true", help="只检查是否需要更新（不写入）")
    p.add_argument("--quiet", action="store_true", help="静默模式（不输出提示文本）")
    return p.parse_args(argv)


def rel(root: Path, p: Path) -> str:
    return os.path.relpath(str(p), str(root))

def count_csv(value: str) -> int:
    return len([p.strip() for p in str(value or "").split(",") if p.strip()])


def render_specs_index(root: Path, superagents_dir: Path) -> str:
    items: list[tuple[str, str, str, str]] = []
    specs_dir = superagents_dir / "specs"
    if specs_dir.exists():
        for spec_path in specs_dir.glob("*/*/spec.md"):
            domain = spec_path.parent.parent.name
            capability = spec_path.parent.name
            text = spec_path.read_text(encoding="utf-8")
            title = extract_frontmatter_value(text, "title") or f"{domain}/{capability}"
            status = extract_frontmatter_value(text, "status") or "unknown"
            items.append((domain, capability, title, status))
    items.sort()

    lines: list[str] = [
        "<!-- generated by sa_index.py; do not edit -->",
        "# Specs Index",
        "",
    ]
    if not items:
        lines += ["- （暂无 specs）", ""]
        return "\n".join(lines)

    current_domain = None
    for domain, capability, title, status in items:
        if domain != current_domain:
            if current_domain is not None:
                lines.append("")
            lines.append(f"## {domain}")
            lines.append("")
            current_domain = domain
        link = rel(root, superagents_dir / "specs" / domain / capability / "spec.md")
        lines.append(f"- `{capability}` ({status}) - [{title}]({link})")

    lines.append("")
    return "\n".join(lines)


def render_tasks_index(root: Path, superagents_dir: Path) -> str:
    tasks_dir = superagents_dir / "tasks"
    items: list[tuple[int, str, str, str, str, str, str, int, str]] = []
    if tasks_dir.exists():
        for task_dir in tasks_dir.iterdir():
            if not task_dir.is_dir():
                continue
            m = sa_id.LEADING_ID_RE.match(task_dir.name)
            if not m:
                continue
            try:
                numeric_id = int(m.group("id"))
            except ValueError:
                continue

            change_md = task_dir / "change" / "change.md"
            plan_md = task_dir / "plan" / "task.md"
            runs_dir = task_dir / "runs"

            title = task_dir.name
            change_status = "unknown"
            plan_status = "unknown"
            clarity = ""
            readiness = ""
            spec_refs = ""
            risk_level = ""

            if change_md.exists():
                change_text = change_md.read_text(encoding="utf-8")
                title = extract_frontmatter_value(change_text, "title") or title
                change_status = extract_frontmatter_value(change_text, "status") or change_status
                clarity = extract_frontmatter_value(change_text, "clarity_score") or ""
                spec_refs = extract_frontmatter_value(change_text, "spec_refs") or ""
                risk_level = extract_frontmatter_value(change_text, "risk_level") or ""

            if plan_md.exists():
                plan_text = plan_md.read_text(encoding="utf-8")
                plan_status = extract_frontmatter_value(plan_text, "status") or plan_status
                readiness = extract_frontmatter_value(plan_text, "readiness_score") or ""
                # 优先使用 plan 的 spec_refs/risk_level（若 change 缺失）
                if not spec_refs:
                    spec_refs = extract_frontmatter_value(plan_text, "spec_refs") or ""
                if not risk_level:
                    risk_level = extract_frontmatter_value(plan_text, "risk_level") or ""

            run_files = []
            latest_run_status = "unknown"
            if runs_dir.exists():
                run_files = sorted([p for p in runs_dir.glob("*.md") if p.is_file()])
                if run_files:
                    latest_text = run_files[-1].read_text(encoding="utf-8")
                    latest_run_status = extract_frontmatter_value(latest_text, "status") or latest_run_status

            items.append(
                (
                    numeric_id,
                    task_dir.name,
                    title,
                    change_status,
                    plan_status,
                    clarity,
                    readiness,
                    len(run_files),
                    latest_run_status,
                )
            )

    items.sort(key=lambda x: x[0])
    lines: list[str] = [
        "<!-- generated by sa_index.py; do not edit -->",
        "# Tasks Index",
        "",
    ]
    if not items:
        lines += ["- （暂无 tasks）", ""]
        return "\n".join(lines)

    for _, name, title, change_status, plan_status, clarity, readiness, run_count, latest_run_status in items:
        change_link = rel(root, superagents_dir / "tasks" / name / "change" / "change.md")
        plan_link = rel(root, superagents_dir / "tasks" / name / "plan" / "task.md")
        extra = f"chg={change_status}, plan={plan_status}, runs={run_count}/{latest_run_status}"
        if clarity:
            extra += f", clarity={clarity}"
        if readiness:
            extra += f", ready={readiness}"
        lines.append(f"- `{name}` ({extra}) - [{title}]({change_link}) ([plan]({plan_link}))")

    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str, *, check: bool) -> bool:
    if path.exists():
        old = path.read_text(encoding="utf-8")
        if old == content:
            return False
    if check:
        return True
    write_text_atomic(path, content)
    return True


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    root = Path(args.root).resolve()
    superagents_dir = root / args.dir
    wiki_dir = superagents_dir / ".sa" / "wiki"
    wiki_dir.mkdir(parents=True, exist_ok=True)

    specs_index_path = wiki_dir / "specs-index.generated.md"
    tasks_index_path = wiki_dir / "tasks-index.generated.md"

    specs_index = render_specs_index(root, superagents_dir)
    tasks_index = render_tasks_index(root, superagents_dir)

    changed = False
    changed |= write_if_changed(specs_index_path, specs_index, check=bool(args.check))
    changed |= write_if_changed(tasks_index_path, tasks_index, check=bool(args.check))

    if args.check and changed:
        if not args.quiet:
            print("索引需要更新")
        return 1
    if not args.quiet:
        print("索引已更新" if changed else "索引无需更新")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(__import__("sys").argv[1:]))
